# Generated by Django 3.2 on 2022-03-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-default', '-id'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
