"""
Django settings for restoraunt_app project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-og5zxmk^g4v9^@amno65by@bs&slfr_bozhjg$gq2e#%o02o=+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "dev1.itpw.ru", "restoraunt_app.itpw.ru"]

APP_PROTOCOL = "http"
APP_DOMEN = "dev1.itpw.ru"
APP_PORT = "8005"

# APPLICATION_ROOT_URL = "http://127.0.0.1:8000"
APP_ROOT_URL = f"{APP_PROTOCOL}://{APP_DOMEN}" + (f":{APP_PORT}" if APP_PORT != "80" else "")

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_jwt',
    'pyfcm',
    'accounts.apps.AccountsConfig',
    'app_info.apps.AppInfoConfig',
    'configurations.apps.ConfigurationsConfig',
    'menu.apps.MenuConfig',
    'itpwlib'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restoraunt_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restoraunt_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DATE_INPUT_FORMATS': ["%d.%m.%Y"],
    'DATETIME_INPUT_FORMATS': ["%d.%m.%Y %H:%M"],
    'DATETIME_FORMAT': "%d.%m.%Y %H:%M",
    'DATE_FORMAT': "%d.%m.%Y",
    'TIME_INPUT_FORMATS': ["%H:%M"],
    'TIME_FORMAT': "%H:%M",
    'EXCEPTION_HANDLER': 'restoraunt_app.exception_handlers.custom_exception_handler',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json'
}

JWT_AUTH = {
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': False,
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
}

CORS_ORIGIN_ALLOW_ALL = True

AUTH_USER_MODEL = "accounts.User"

FCM_DJANGO_SETTINGS = {
    # dev
    # "FCM_SERVER_KEY": "AAAAwG4xCCM:APA91bF_CBMWDycSulls_iN5pGhIrsAlS3QzcoxTylQb4dDhuisNQSOFX2h-x0FezmQ9F2bI5x8uDRyOROIcEu4dMotnNQkSVHJ06-GvUvT-p0SNAdwiSMN8PKWlRHs1nyBuq-mfi60E"
    # prod
    "FCM_SERVER_KEY": "AAAAdTtQD5U:APA91bFxhq5pohJFmfwE_nLZ5uLxuGgvfZTHTsW_9VSh3-ALdjl-XpsgyrbKSdOFF2-zIus8EFWFaGkU2r4ZWTNiZ_VSdOa5ncsO-Cpjt-A1M5gXkmI-BTaESUJpEf1N5Vr3o9miKEkJ"
}

APP_PROTOCOL = "http"
APP_DOMEN = "dev1.itpw.ru"
APP_PORT = "8004"

# APPLICATION_ROOT_URL = "http://127.0.0.1:8000"
APP_ROOT_URL = f"{APP_PROTOCOL}://{APP_DOMEN}" + (f":{APP_PORT}" if APP_PORT != "80" else "")

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumPasswordValidation'
    # }
]

AUTH_USER_MODEL = "accounts.User"

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = Path(BASE_DIR, "static")
MEDIA_ROOT = Path(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FCM_DJANGO_SETTINGS = {
    # dev
    # "FCM_SERVER_KEY": "AAAAwG4xCCM:APA91bF_CBMWDycSulls_iN5pGhIrsAlS3QzcoxTylQb4dDhuisNQSOFX2h-x0FezmQ9F2bI5x8uDRyOROIcEu4dMotnNQkSVHJ06-GvUvT-p0SNAdwiSMN8PKWlRHs1nyBuq-mfi60E"
    # prod
    "FCM_SERVER_KEY": "AAAAdTtQD5U:APA91bFxhq5pohJFmfwE_nLZ5uLxuGgvfZTHTsW_9VSh3-ALdjl-XpsgyrbKSdOFF2-zIus8EFWFaGkU2r4ZWTNiZ_VSdOa5ncsO-Cpjt-A1M5gXkmI-BTaESUJpEf1N5Vr3o9miKEkJ"
}

# SMS Aero
SMS_API_KEY = '096YFJG7tI1JBulyLFBEoaIV71h'
SMS_EMAIL = 'teluridkadmiy@gmail.com'
SMS_API_PROTOCOL = 'https'
SMS_SIGN_DEFAULT = 'SMS Aero'
SMS_SEND_URL = f'{SMS_API_PROTOCOL}://{SMS_EMAIL}:{SMS_API_KEY}@gate.smsaero.ru/v2/sms/send/'

# Email backends
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'developer.itpw@gmail.com'
EMAIL_HOST_PASSWORD = 'qwddwavunucaoima'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# default files
DEFAULT_FILES_DIR = "defaults"
DEFAULT_NEED_UPDATE_IMG = os.path.join(DEFAULT_FILES_DIR, "need_update.jpg")
DEFAULT_SERVER_MAINTENANCE_IMG = os.path.join(DEFAULT_FILES_DIR, "server_maintenance.jpg")
