# Generated by Django 3.2 on 2022-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('ios_latest_version', models.IntegerField(verbose_name='Последняя IOS версия')),
                ('ios_min_version', models.IntegerField(verbose_name='Минимальная IOS версия')),
                ('ios_app_href', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на приложение IOS')),
                ('android_app_latest_version', models.IntegerField(verbose_name='Последняя Android версия')),
                ('android_app_min_version', models.IntegerField(verbose_name='Минимальная Android версия')),
                ('android_app_href', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на приложение Android')),
                ('actual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации мобильных приложений',
                'ordering': ['-actual', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServerMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Причина')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Технические работы',
                'verbose_name_plural': 'Технические работы',
                'ordering': ['-start'],
            },
        ),
    ]
