# Generated by Django 3.2 on 2022-03-03 16:42

import app_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to=app_info.models.faq_img_path)),
                ('href', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['title'],
            },
        ),
    ]
